[package]
name = "common"
version = "0.1.0"
authors = ["Harsh <harsh.pathak53@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.8"
serde = "*"
serde_json = "*"
actix-http = "0.2.10"